package sample.spring.batch.db.generate.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import sample.spring.batch.db.generate.dto.Db1;
import sample.spring.batch.db.generate.dto.Db1Example;

public interface Db1Mapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table public.db1
	 *
	 * @mbggenerated Sat Mar 11 20:05:08 JST 2017
	 */
	int countByExample(Db1Example example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table public.db1
	 *
	 * @mbggenerated Sat Mar 11 20:05:08 JST 2017
	 */
	int deleteByExample(Db1Example example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table public.db1
	 *
	 * @mbggenerated Sat Mar 11 20:05:08 JST 2017
	 */
	int insert(Db1 record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table public.db1
	 *
	 * @mbggenerated Sat Mar 11 20:05:08 JST 2017
	 */
	int insertSelective(Db1 record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table public.db1
	 *
	 * @mbggenerated Sat Mar 11 20:05:08 JST 2017
	 */
	List<Db1> selectByExample(Db1Example example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table public.db1
	 *
	 * @mbggenerated Sat Mar 11 20:05:08 JST 2017
	 */
	int updateByExampleSelective(@Param("record") Db1 record, @Param("example") Db1Example example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table public.db1
	 *
	 * @mbggenerated Sat Mar 11 20:05:08 JST 2017
	 */
	int updateByExample(@Param("record") Db1 record, @Param("example") Db1Example example);
}