package sample.spring.batch.db.generate.dto;

public class Db1 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.db1.id
     *
     * @mbggenerated Sat Mar 11 20:05:08 JST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.db1.name
     *
     * @mbggenerated Sat Mar 11 20:05:08 JST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.db1.id
     *
     * @return the value of public.db1.id
     *
     * @mbggenerated Sat Mar 11 20:05:08 JST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.db1.id
     *
     * @param id the value for public.db1.id
     *
     * @mbggenerated Sat Mar 11 20:05:08 JST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.db1.name
     *
     * @return the value of public.db1.name
     *
     * @mbggenerated Sat Mar 11 20:05:08 JST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.db1.name
     *
     * @param name the value for public.db1.name
     *
     * @mbggenerated Sat Mar 11 20:05:08 JST 2017
     */
    public void setName(String name) {
        this.name = name;
    }
}