package sample.spring.batch.db.generator.dto;

public class Db1 {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column public.db1.id
     *
     * @mbg.generated Sun Jul 15 11:06:15 JST 2018
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column public.db1.name
     *
     * @mbg.generated Sun Jul 15 11:06:15 JST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column public.db1.id
     *
     * @return the value of public.db1.id
     * @mbg.generated Sun Jul 15 11:06:15 JST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column public.db1.id
     *
     * @param id
     *            the value for public.db1.id
     * @mbg.generated Sun Jul 15 11:06:15 JST 2018
     */
    public void setId(final Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column public.db1.name
     *
     * @return the value of public.db1.name
     * @mbg.generated Sun Jul 15 11:06:15 JST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column public.db1.name
     *
     * @param name
     *            the value for public.db1.name
     * @mbg.generated Sun Jul 15 11:06:15 JST 2018
     */
    public void setName(final String name) {
        this.name = name;
    }
}
