package sample.spring.batch.db.generator.dto;

public class Db2 {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.db2.id
	 * @mbg.generated  Mon Jul 23 23:33:50 JST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.db2.name
	 * @mbg.generated  Mon Jul 23 23:33:50 JST 2018
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.db2.id
	 * @return  the value of public.db2.id
	 * @mbg.generated  Mon Jul 23 23:33:50 JST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.db2.id
	 * @param id  the value for public.db2.id
	 * @mbg.generated  Mon Jul 23 23:33:50 JST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.db2.name
	 * @return  the value of public.db2.name
	 * @mbg.generated  Mon Jul 23 23:33:50 JST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.db2.name
	 * @param name  the value for public.db2.name
	 * @mbg.generated  Mon Jul 23 23:33:50 JST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}
}